version: '3.8'

services:
    webdav:
        container_name: webdav
        build:
            context: .
        volumes:
            - ./data:/data
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - TIMEOUTS_S=${TIMEOUTS_S}
            - CLIENT_MAX_BODY_SIZE=${CLIENT_MAX_BODY_SIZE}
        ports:
          - 80:80
        restart: unless-stopped
        
