version: '3.8'

services:
    webdav:
        container_name: webdav
        build:
            context: .
        volumes:
            - ./data:/data
        ports:
          - 8080:443
        restart: unless-stopped
        
