version: '3.8'

services:
    webdav:
        container_name: webdav
        image: paolobasso/webdav
        volumes:
            - ./data:/data
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.webdav.service=webdav"
            - "traefik.http.routers.webdav.tls=true"
            - "traefik.http.routers.webdav.tls.certresolver=dns-cloudflare"
            - "traefik.http.routers.webdav.entrypoints=websecure"
            - "traefik.http.services.webdav.loadbalancer.server.port=80"
            - "traefik.http.routers.webdav.middlewares=authelia@docker"
        networks:
            - web_proxy
      
networks:
    web_proxy:
        external:
            name: web_proxy