---
name: 'build publish images'

on:
  push:
    branches:
      - main
    #branches-ignore:
    #  - '**'
    paths-ignore:
      - '**.md'
      - 'traefik-authelia-example/**'
      - 'docker-compose.yml'
      - '.env.example'
      - '.gitignore'
      - 'LICENSE'
      - '.github/workflows/update_dockerhub_readme.yml'
  workflow_dispatch:

jobs:
  build_publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: amd64,arm64,arm/v7

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and publish
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          pull: true
          push: true
          tags: ${{ secrets.IMAGE_NAME }}:latest